{
 "title": "Observer API",
 "description": "Dashboard for observer API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(observer_last_fetched_pulse, namespace)"
   },
   {
    "name": "handler",
    "label": "Handler",
    "query": "label_values(echo_http_requests_total, handler)"
   }
  ]
 },
 "panels": [
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic - Req/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(echo_http_requests_total{namespace=\"$namespace\", handler=~\"$handler\", handler!=\"/metrics\"}[2m])) by (job)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Traffic - Req/s by handler",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(echo_http_requests_total{namespace=\"$namespace\", handler=~\"$handler\", handler!=\"/metrics\"}[2m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ method }} {{handler}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Errors - % (5xx)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(echo_http_requests_total{namespace=\"$namespace\", handler=~\"$handler\", handler!=\"/metrics\", status=\"5xx\"}[5m]))/sum(rate(echo_http_requests_total{namespace=\"$namespace\", handler=~\"$handler\", handler!=\"/metrics\"}[5m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ method }} {{handler}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Errors - % by handler (5xx)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(echo_http_requests_total{namespace=\"$namespace\", handler=~\"$handler\", handler!=\"/metrics\", status=\"5xx\"}[5m])) by (method, handler)/sum(rate(echo_http_requests_total{namespace=\"$namespace\", handler=~\"$handler\", handler!=\"/metrics\"}[5m])) by (method, handler)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ method }} {{handler}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Latêncy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Latency - General",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (le) (rate(echo_http_request_duration_seconds_bucket{namespace=\"$namespace\", handler=~\"$handler\", handler!=\"/metrics\"}[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(echo_http_request_duration_seconds_bucket{namespace=\"$namespace\", handler=~\"$handler\", handler!=\"/metrics\"}[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(echo_http_request_duration_seconds_bucket{namespace=\"$namespace\", handler=~\"$handler\", handler!=\"/metrics\"}[5m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Latency by handler",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (method, handler, le) (rate(echo_http_request_duration_seconds_bucket{namespace=\"$namespace\", handler=~\"$handler\", handler!=\"/metrics\"}[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ method }} {{ handler }} - p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (method, handler, le) (rate(echo_http_request_duration_seconds_bucket{namespace=\"$namespace\", handler=~\"$handler\", handler!=\"/metrics\"}[5m])))",
     "legendFormat": "{{ method }} {{ handler }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (method, handler, le) (rate(echo_http_request_duration_seconds_bucket{namespace=\"$namespace\", handler=~\"$handler\", handler!=\"/metrics\"}[5m])))",
     "legendFormat": "{{ method }} {{ handler }} - p99"
    }
   ]
  }
 ]
}