{
 "title": "Observer",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(observer_last_fetched_pulse, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Migration addresses available",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "observer_addresses_stored_total{namespace=\"$namespace\"} - observer_vestings_stored_total{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last pulse number",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "observer_last_fetched_pulse{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Transfers stored",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(observer_transfers_stored_total{namespace=\"$namespace\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Members stored",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(observer_members_stored_total{namespace=\"$namespace\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Activates stored",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(observer_activates_stored_total{namespace=\"$namespace\"}[2m])"
    }
   ]
  },
  {
   "title": "Balances stored",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(observer_balances_stored_total{namespace=\"$namespace\"}[2m])"
    }
   ]
  },
  {
   "title": "Deactivates stored",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(observer_deactivates_stored_total{namespace=\"$namespace\"}[2m])"
    }
   ]
  },
  {
   "title": "Deposits stored",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(observer_deposits_stored_total{namespace=\"$namespace\"}[2m])"
    }
   ]
  }
 ]
}