{
 "title": "Observer",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Migration addresses available",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "observer_available_migration_addresses_total"
    }
   ]
  },
  {
   "title": "Last pulse number",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "observer_last_sync_pulse" }
   ]
  },
  {
   "title": "Cache size",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "observer_deposit_composer_cached_total"
    },
    {
     "expr": "observer_deposit_transfer_composer_cached_total"
    },
    {
     "expr": "observer_member_composer_cached_total"
    },
    {
     "expr": "observer_member_transfer_composer_cached_total"
    },
    {
     "expr": "observer_migration_address_composer_cached_total"
    },
    {
     "expr": "observer_migration_address_keeper_cached_total"
    }
   ]
  },
  {
   "title": "Average time per pulse",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "observer_processing_duration_seconds_sum/observer_processing_duration_seconds_count"
    },
    {
     "expr": "observer_processing_duration_seconds_sum"
    },
    {
     "expr": "observer_processing_duration_seconds_count"
    }
   ]
  }
 ]
}