ARG GOLANG_VERSION=1.12
FROM golang:${GOLANG_VERSION} AS build
WORKDIR /build

COPY ./ /build
RUN make build-node

FROM debian:buster-slim as app
RUN apt update && apt install -y ca-certificates && apt-get clean all
COPY $PWD/scripts/migrations /migrations
COPY --from=build /build/bin/observer /build/bin/api /build/bin/migrate /usr/local/bin/
