package observer

// Code generated by http://github.com/gojuno/minimock (2.1.9). DO NOT EDIT.

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock"
	"github.com/insolar/insolar/insolar"
	"github.com/insolar/insolar/ledger/heavy/exporter"
)

// HeavyRecordFetcherMock implements HeavyRecordFetcher
type HeavyRecordFetcherMock struct {
	t minimock.Tester

	funcFetch          func(ctx context.Context, p1 insolar.PulseNumber) (m1 map[uint32]*exporter.Record, p2 insolar.PulseNumber, err error)
	inspectFuncFetch   func(ctx context.Context, p1 insolar.PulseNumber)
	afterFetchCounter  uint64
	beforeFetchCounter uint64
	FetchMock          mHeavyRecordFetcherMockFetch
}

// NewHeavyRecordFetcherMock returns a mock for HeavyRecordFetcher
func NewHeavyRecordFetcherMock(t minimock.Tester) *HeavyRecordFetcherMock {
	m := &HeavyRecordFetcherMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.FetchMock = mHeavyRecordFetcherMockFetch{mock: m}
	m.FetchMock.callArgs = []*HeavyRecordFetcherMockFetchParams{}

	return m
}

type mHeavyRecordFetcherMockFetch struct {
	mock               *HeavyRecordFetcherMock
	defaultExpectation *HeavyRecordFetcherMockFetchExpectation
	expectations       []*HeavyRecordFetcherMockFetchExpectation

	callArgs []*HeavyRecordFetcherMockFetchParams
	mutex    sync.RWMutex
}

// HeavyRecordFetcherMockFetchExpectation specifies expectation struct of the HeavyRecordFetcher.Fetch
type HeavyRecordFetcherMockFetchExpectation struct {
	mock    *HeavyRecordFetcherMock
	params  *HeavyRecordFetcherMockFetchParams
	results *HeavyRecordFetcherMockFetchResults
	Counter uint64
}

// HeavyRecordFetcherMockFetchParams contains parameters of the HeavyRecordFetcher.Fetch
type HeavyRecordFetcherMockFetchParams struct {
	ctx context.Context
	p1  insolar.PulseNumber
}

// HeavyRecordFetcherMockFetchResults contains results of the HeavyRecordFetcher.Fetch
type HeavyRecordFetcherMockFetchResults struct {
	m1  map[uint32]*exporter.Record
	p2  insolar.PulseNumber
	err error
}

// Expect sets up expected params for HeavyRecordFetcher.Fetch
func (mmFetch *mHeavyRecordFetcherMockFetch) Expect(ctx context.Context, p1 insolar.PulseNumber) *mHeavyRecordFetcherMockFetch {
	if mmFetch.mock.funcFetch != nil {
		mmFetch.mock.t.Fatalf("HeavyRecordFetcherMock.Fetch mock is already set by Set")
	}

	if mmFetch.defaultExpectation == nil {
		mmFetch.defaultExpectation = &HeavyRecordFetcherMockFetchExpectation{}
	}

	mmFetch.defaultExpectation.params = &HeavyRecordFetcherMockFetchParams{ctx, p1}
	for _, e := range mmFetch.expectations {
		if minimock.Equal(e.params, mmFetch.defaultExpectation.params) {
			mmFetch.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmFetch.defaultExpectation.params)
		}
	}

	return mmFetch
}

// Inspect accepts an inspector function that has same arguments as the HeavyRecordFetcher.Fetch
func (mmFetch *mHeavyRecordFetcherMockFetch) Inspect(f func(ctx context.Context, p1 insolar.PulseNumber)) *mHeavyRecordFetcherMockFetch {
	if mmFetch.mock.inspectFuncFetch != nil {
		mmFetch.mock.t.Fatalf("Inspect function is already set for HeavyRecordFetcherMock.Fetch")
	}

	mmFetch.mock.inspectFuncFetch = f

	return mmFetch
}

// Return sets up results that will be returned by HeavyRecordFetcher.Fetch
func (mmFetch *mHeavyRecordFetcherMockFetch) Return(m1 map[uint32]*exporter.Record, p2 insolar.PulseNumber, err error) *HeavyRecordFetcherMock {
	if mmFetch.mock.funcFetch != nil {
		mmFetch.mock.t.Fatalf("HeavyRecordFetcherMock.Fetch mock is already set by Set")
	}

	if mmFetch.defaultExpectation == nil {
		mmFetch.defaultExpectation = &HeavyRecordFetcherMockFetchExpectation{mock: mmFetch.mock}
	}
	mmFetch.defaultExpectation.results = &HeavyRecordFetcherMockFetchResults{m1, p2, err}
	return mmFetch.mock
}

//Set uses given function f to mock the HeavyRecordFetcher.Fetch method
func (mmFetch *mHeavyRecordFetcherMockFetch) Set(f func(ctx context.Context, p1 insolar.PulseNumber) (m1 map[uint32]*exporter.Record, p2 insolar.PulseNumber, err error)) *HeavyRecordFetcherMock {
	if mmFetch.defaultExpectation != nil {
		mmFetch.mock.t.Fatalf("Default expectation is already set for the HeavyRecordFetcher.Fetch method")
	}

	if len(mmFetch.expectations) > 0 {
		mmFetch.mock.t.Fatalf("Some expectations are already set for the HeavyRecordFetcher.Fetch method")
	}

	mmFetch.mock.funcFetch = f
	return mmFetch.mock
}

// When sets expectation for the HeavyRecordFetcher.Fetch which will trigger the result defined by the following
// Then helper
func (mmFetch *mHeavyRecordFetcherMockFetch) When(ctx context.Context, p1 insolar.PulseNumber) *HeavyRecordFetcherMockFetchExpectation {
	if mmFetch.mock.funcFetch != nil {
		mmFetch.mock.t.Fatalf("HeavyRecordFetcherMock.Fetch mock is already set by Set")
	}

	expectation := &HeavyRecordFetcherMockFetchExpectation{
		mock:   mmFetch.mock,
		params: &HeavyRecordFetcherMockFetchParams{ctx, p1},
	}
	mmFetch.expectations = append(mmFetch.expectations, expectation)
	return expectation
}

// Then sets up HeavyRecordFetcher.Fetch return parameters for the expectation previously defined by the When method
func (e *HeavyRecordFetcherMockFetchExpectation) Then(m1 map[uint32]*exporter.Record, p2 insolar.PulseNumber, err error) *HeavyRecordFetcherMock {
	e.results = &HeavyRecordFetcherMockFetchResults{m1, p2, err}
	return e.mock
}

// Fetch implements HeavyRecordFetcher
func (mmFetch *HeavyRecordFetcherMock) Fetch(ctx context.Context, p1 insolar.PulseNumber) (m1 map[uint32]*exporter.Record, p2 insolar.PulseNumber, err error) {
	mm_atomic.AddUint64(&mmFetch.beforeFetchCounter, 1)
	defer mm_atomic.AddUint64(&mmFetch.afterFetchCounter, 1)

	if mmFetch.inspectFuncFetch != nil {
		mmFetch.inspectFuncFetch(ctx, p1)
	}

	mm_params := &HeavyRecordFetcherMockFetchParams{ctx, p1}

	// Record call args
	mmFetch.FetchMock.mutex.Lock()
	mmFetch.FetchMock.callArgs = append(mmFetch.FetchMock.callArgs, mm_params)
	mmFetch.FetchMock.mutex.Unlock()

	for _, e := range mmFetch.FetchMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.m1, e.results.p2, e.results.err
		}
	}

	if mmFetch.FetchMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmFetch.FetchMock.defaultExpectation.Counter, 1)
		mm_want := mmFetch.FetchMock.defaultExpectation.params
		mm_got := HeavyRecordFetcherMockFetchParams{ctx, p1}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmFetch.t.Errorf("HeavyRecordFetcherMock.Fetch got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmFetch.FetchMock.defaultExpectation.results
		if mm_results == nil {
			mmFetch.t.Fatal("No results are set for the HeavyRecordFetcherMock.Fetch")
		}
		return (*mm_results).m1, (*mm_results).p2, (*mm_results).err
	}
	if mmFetch.funcFetch != nil {
		return mmFetch.funcFetch(ctx, p1)
	}
	mmFetch.t.Fatalf("Unexpected call to HeavyRecordFetcherMock.Fetch. %v %v", ctx, p1)
	return
}

// FetchAfterCounter returns a count of finished HeavyRecordFetcherMock.Fetch invocations
func (mmFetch *HeavyRecordFetcherMock) FetchAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFetch.afterFetchCounter)
}

// FetchBeforeCounter returns a count of HeavyRecordFetcherMock.Fetch invocations
func (mmFetch *HeavyRecordFetcherMock) FetchBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFetch.beforeFetchCounter)
}

// Calls returns a list of arguments used in each call to HeavyRecordFetcherMock.Fetch.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmFetch *mHeavyRecordFetcherMockFetch) Calls() []*HeavyRecordFetcherMockFetchParams {
	mmFetch.mutex.RLock()

	argCopy := make([]*HeavyRecordFetcherMockFetchParams, len(mmFetch.callArgs))
	copy(argCopy, mmFetch.callArgs)

	mmFetch.mutex.RUnlock()

	return argCopy
}

// MinimockFetchDone returns true if the count of the Fetch invocations corresponds
// the number of defined expectations
func (m *HeavyRecordFetcherMock) MinimockFetchDone() bool {
	for _, e := range m.FetchMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.FetchMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterFetchCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcFetch != nil && mm_atomic.LoadUint64(&m.afterFetchCounter) < 1 {
		return false
	}
	return true
}

// MinimockFetchInspect logs each unmet expectation
func (m *HeavyRecordFetcherMock) MinimockFetchInspect() {
	for _, e := range m.FetchMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to HeavyRecordFetcherMock.Fetch with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.FetchMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterFetchCounter) < 1 {
		if m.FetchMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to HeavyRecordFetcherMock.Fetch")
		} else {
			m.t.Errorf("Expected call to HeavyRecordFetcherMock.Fetch with params: %#v", *m.FetchMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcFetch != nil && mm_atomic.LoadUint64(&m.afterFetchCounter) < 1 {
		m.t.Error("Expected call to HeavyRecordFetcherMock.Fetch")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *HeavyRecordFetcherMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockFetchInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *HeavyRecordFetcherMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *HeavyRecordFetcherMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockFetchDone()
}
